[project]
authors = ["ESPR3SS0 <98864173+ESPR3SS0@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "vanilla_env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
torchaudio = ">=2.5.1,<3"
tqdm = ">=4.67.1,<5"
torchinfo = ">=1.8.0,<2"
cyclopts = ">=3.9.1,<4"
h5py = ">=3.13.0,<4"
scikit-learn = ">=1.6.1,<2"




[system-requirements]
cuda = "12"





