[project]
authors = ["ESPR3SS0 <98864173+ESPR3SS0@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "vanilla_env"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12"

[tasks]

[dependencies]
tqdm = ">=4.67.1,<5"
cyclopts = ">=3.9.1,<4"
pytorch-gpu = ">=2.7.0,<3"
torchinfo = ">=1.8.0,<2"
h5py = ">=3.13.0,<4"
scikit-learn = ">=1.6.1,<2"
nvitop = ">=1.5.0,<2"







