# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/phu/repos/PytorchModClassNew/RadioFINN/notebooks/Radio_27ML/output/example_output_radio_27ml_w8a8_tidy_ZCU104/stitched_ip/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0.xci
# IP: The module: 'finn_design_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/phu/repos/PytorchModClassNew/RadioFINN/notebooks/Radio_27ML/output/example_output_radio_27ml_w8a8_tidy_ZCU104/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/phu/repos/PytorchModClassNew/RadioFINN/notebooks/Radio_27ML/output/example_output_radio_27ml_w8a8_tidy_ZCU104/stitched_ip/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0.xci
# IP: The module: 'finn_design_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/phu/repos/PytorchModClassNew/RadioFINN/notebooks/Radio_27ML/output/example_output_radio_27ml_w8a8_tidy_ZCU104/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
